### ISSUE TITLE
Improve handle of Subscriptions

### ISSUE THREAD

**Issue by AdrianKBL** [hgraph-io/sdk#20]
Good morning,

We are facing significant issues with managing subscriptions on our end. Occasionally, subscriptions are not being closed correctly, subscriptions to be able to closed you can not get the promise returned and execute it, since some times the SDK is not returning a promise itself but other yes...etc. This is resulting in balances from one account being printed into another. This issue has consumed a considerable amount of our time and continues to occur.

What I would suggest is taking a look about how `Supabase` manage this, I think it's pretty good and give a lot of different tools to manage the active subscriptions, close all of them at once, close each one individually...etc.

https://supabase.com/docs/reference/javascript/subscribe

**Comment by hgraphql** [comment]
Thanks for the feedback and suggestion!

Closing this as merged in https://github.com/hgraph-io/sdk/pull/22 and published in v0.8.0

If you run into any issues feel free to open again.
