### ISSUE TITLE
Add type for Client & SubscriptionClient

### ISSUE THREAD

**Issue by AdrianKBL** [hgraph-io/sdk#23]
Whenever we try to use SubscriptionClient, we do not get autocomplete suggestions for its methods. This issue arises because both Client and SubscriptionClient are typed as any.

![image](https://github.com/user-attachments/assets/dff6f69f-eebe-4d9c-a3c6-62bfadfcaa6c)
![image](https://github.com/user-attachments/assets/a0c88b1a-a5bc-4412-8429-93499d9a979d)

**Comment by tmctl** [comment]
@AdrianKBL just pushed an update to npm here - https://www.npmjs.com/package/@hgraph.io/sdk

the update was a small change here - https://github.com/hgraph-io/sdk/pull/27

does this resolve the issue or should be keep digging?

**Comment by AdrianKBL** [comment]
Added the type. Thanks.
